---
- name: Laravel Sail Project Setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    # Project directory
    projects_dir: "/var/www/projects"
    shared_group: "www-data"
    
    # Current user
    current_user: "{{ target_user | default(lookup('env', 'SUDO_USER') | default(ansible_user_id, true)) }}"
    current_home: "{{ '/root' if current_user == 'root' else '/home/' + current_user }}"
    
    ansible_remote_tmp: /tmp

    projects:
      - { name: "zone", repo: "git@github.com:visio-soft/zone.git" }
      - { name: "gate", repo: "git@github.com:visio-soft/gate.git" }

  tasks:
    # ==================================================================
    # USER SETUP
    # ==================================================================
    - name: Add current user to www-data and docker groups
      user:
        name: "{{ current_user }}"
        groups: "{{ shared_group }},docker"
        append: yes

    # ==================================================================
    # SSH KEY FOR GITHUB
    # ==================================================================
    - name: Generate SSH Key if not exists
      become_user: "{{ current_user }}"
      shell: |
        if [ ! -f {{ current_home }}/.ssh/id_ed25519 ]; then
          mkdir -p {{ current_home }}/.ssh
          ssh-keygen -t ed25519 -f {{ current_home }}/.ssh/id_ed25519 -N ""
        fi
      args:
        creates: "{{ current_home }}/.ssh/id_ed25519"

    - name: Read Public Key
      command: "cat {{ current_home }}/.ssh/id_ed25519.pub"
      register: ssh_key
      changed_when: false

    - name: 🛑 GITHUB KEY CONFIRMATION 🛑
      debug:
        msg: 
          - "################################################################"
          - "KEY: {{ ssh_key.stdout }}"
          - "################################################################"
          - "Please add this key to GitHub: https://github.com/settings/ssh/new"
          - "################################################################"

    - name: WAITING FOR CONFIRMATION
      pause:
        prompt: "❗ Press ENTER after adding the Key to GitHub..."

    # ==================================================================
    # DATABASE SETUP (Not needed - using Sail containers)
    # ==================================================================
    # Laravel Sail will manage databases via Docker containers

    # ==================================================================
    # SHARED DIRECTORY SETUP
    # ==================================================================
    - name: Create Shared Projects Directory
      file:
        path: "{{ projects_dir }}"
        state: directory
        owner: root
        group: "{{ shared_group }}"
        mode: '2775'  # setgid bit - new files inherit group

    - name: Clone Projects
      become_user: "{{ current_user }}"
      become_flags: '-i'
      git:
        repo: "{{ item.repo }}"
        dest: "{{ projects_dir }}/{{ item.name }}"
        accept_hostkey: yes
        version: main
        force: yes
      loop: "{{ projects }}"

    - name: Configure Projects for Laravel Sail
      become_user: "{{ current_user }}"
      become_flags: '-i'
      shell: |
        # Copy .env.example to .env if not exists
        cp -n .env.example .env || true
        
        # Install composer dependencies first
        composer install --no-interaction --prefer-dist
        
        # Install Laravel Sail if not present in composer.json
        if ! grep -q "laravel/sail" composer.json; then
          composer require laravel/sail --dev
        fi
        
        # Install Sail configuration (pgsql, redis)
        php artisan sail:install --with=pgsql,redis
        
        # Update .env for Sail
        sed -i "s/^DB_HOST=.*/DB_HOST=pgsql/" .env
        sed -i "s/^DB_DATABASE=.*/DB_DATABASE={{ item.name }}_db/" .env
        sed -i "s/^DB_USERNAME=.*/DB_USERNAME=sail/" .env
        sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=password/" .env
        sed -i "s|^APP_URL=.*|APP_URL=http://localhost|" .env
        sed -i "s/^REDIS_HOST=.*/REDIS_HOST=redis/" .env
        sed -i "s/^QUEUE_CONNECTION=.*/QUEUE_CONNECTION=redis/" .env
        
        # Add APP_PORT to .env if not exists
        if ! grep -q "^APP_PORT=" .env; then
          echo "APP_PORT={{ 8000 + ansible_loop.index0 }}" >> .env
        fi
        
        # Generate application key
        php artisan key:generate || true
      args:
        chdir: "{{ projects_dir }}/{{ item.name }}"
      loop: "{{ projects }}"
      loop_control:
        extended: yes

    # ==================================================================
    # SHARED PERMISSIONS (any www-data user can edit)
    # ==================================================================
    - name: Set Project Directory Permissions
      file:
        path: "{{ projects_dir }}/{{ item.name }}"
        state: directory
        recurse: yes
        group: "{{ shared_group }}"
        mode: 'g+rwX'  # group read/write/execute
      loop: "{{ projects }}"

    - name: Set Storage Permissions (writable by all)
      file:
        path: "{{ projects_dir }}/{{ item.name }}/storage"
        state: directory
        recurse: yes
        group: "{{ shared_group }}"
        mode: '2775'  # setgid + rwx for group
      loop: "{{ projects }}"

    - name: Set Bootstrap Cache Permissions
      file:
        path: "{{ projects_dir }}/{{ item.name }}/bootstrap/cache"
        state: directory
        recurse: yes
        group: "{{ shared_group }}"
        mode: '2775'
      loop: "{{ projects }}"
      ignore_errors: yes

    # ==================================================================
    # START SAIL CONTAINERS
    # ==================================================================
    - name: Start Laravel Sail Containers
      become_user: "{{ current_user }}"
      become_flags: '-i'
      shell: |
        ./vendor/bin/sail up -d
      args:
        chdir: "{{ projects_dir }}/{{ item.name }}"
      loop: "{{ projects }}"
      environment:
        HOME: "{{ current_home }}"

    - name: Wait for containers to be ready
      pause:
        seconds: 10

    - name: Run migrations and setup in Sail
      become_user: "{{ current_user }}"
      become_flags: '-i'
      shell: |
        ./vendor/bin/sail artisan migrate --force
        ./vendor/bin/sail artisan storage:link
        ./vendor/bin/sail npm install
        ./vendor/bin/sail npm run build
      args:
        chdir: "{{ projects_dir }}/{{ item.name }}"
      loop: "{{ projects }}"
      ignore_errors: yes
      environment:
        HOME: "{{ current_home }}"

    # ==================================================================
    # FINAL STATUS
    # ==================================================================
    - name: Get Running Containers
      become_user: "{{ current_user }}"
      shell: docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      register: container_status
      changed_when: false

    - name: 🏁 PROJECT SETUP COMPLETE 🏁
      debug:
        msg: 
          - "All projects configured with Laravel Sail!"
          - "Projects directory: {{ projects_dir }}"
          - ""
          - "Running Docker Containers:"
          - "{{ container_status.stdout }}"
          - ""
          - "Access your applications:"
          - "  - zone: http://localhost:8000"
          - "  - gate: http://localhost:8001"
          - ""
          - "Useful Sail commands:"
          - "  ./vendor/bin/sail up -d    # Start containers"
          - "  ./vendor/bin/sail down     # Stop containers"
          - "  ./vendor/bin/sail artisan  # Run artisan commands"
          - "  ./vendor/bin/sail composer # Run composer"
          - "  ./vendor/bin/sail npm      # Run npm"
          - "  ./vendor/bin/sail shell    # Access container shell"
