---
- name: Laravel Project Setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    # Shared directory - all www-data users can access
    projects_dir: "/var/www/projects"
    shared_group: "www-data"
    
    # Current user - can be passed as extra-var or detected from environment
    current_user: "{{ target_user | default(lookup('env', 'SUDO_USER') | default(ansible_user_id, true)) }}"
    current_home: "{{ '/root' if current_user == 'root' else '/home/' + current_user }}"
    
    composer_bin: "/usr/local/bin/composer"
    php_bin: "/usr/bin/php"
    php_fpm_sock: "/run/php/php8.4-fpm.sock"
    db_pass: "secret"
    ansible_remote_tmp: /tmp

    projects:
      - { name: "zone", repo: "git@github.com:visio-soft/zone.git", db: "zone_db", user: "zone_user" }
      - { name: "gate", repo: "git@github.com:visio-soft/gate.git", db: "gate_db", user: "gate_user" }

  tasks:
    # ==================================================================
    # USER SETUP - Add current user to www-data group
    # ==================================================================
    - name: Add current user to www-data group
      user:
        name: "{{ current_user }}"
        groups: "{{ shared_group }}"
        append: yes

    # ==================================================================
    # SSH KEY FOR GITHUB
    # ==================================================================
    - name: Generate SSH Key if not exists
      become_user: "{{ current_user }}"
      shell: |
        if [ ! -f {{ current_home }}/.ssh/id_ed25519 ]; then
          mkdir -p {{ current_home }}/.ssh
          ssh-keygen -t ed25519 -f {{ current_home }}/.ssh/id_ed25519 -N ""
        fi
      args:
        creates: "{{ current_home }}/.ssh/id_ed25519"

    - name: Read Public Key
      command: "cat {{ current_home }}/.ssh/id_ed25519.pub"
      register: ssh_key
      changed_when: false

    - name: 🛑 GITHUB KEY CONFIRMATION 🛑
      debug:
        msg: 
          - "################################################################"
          - "KEY: {{ ssh_key.stdout }}"
          - "################################################################"
          - "Please add this key to GitHub: https://github.com/settings/ssh/new"
          - "################################################################"

    - name: WAITING FOR CONFIRMATION
      pause:
        prompt: "❗ Press ENTER after adding the Key to GitHub..."

    # ==================================================================
    # DATABASE SETUP
    # ==================================================================
    - name: Setup Database Users and Databases
      become_user: postgres
      block:
        - postgresql_user: { name: "{{ item.user }}", password: "{{ db_pass }}" }
          loop: "{{ projects }}"
        - postgresql_db: { name: "{{ item.db }}", owner: "{{ item.user }}" }
          loop: "{{ projects }}"

    # ==================================================================
    # SHARED DIRECTORY SETUP
    # ==================================================================
    - name: Create Shared Projects Directory
      file:
        path: "{{ projects_dir }}"
        state: directory
        owner: root
        group: "{{ shared_group }}"
        mode: '2775'  # setgid bit - new files inherit group

    - name: Clone Projects
      become_user: "{{ current_user }}"
      become_flags: '-i'
      git:
        repo: "{{ item.repo }}"
        dest: "{{ projects_dir }}/{{ item.name }}"
        accept_hostkey: yes
        version: main
        force: yes
      loop: "{{ projects }}"

    - name: Configure Projects (.env, Composer, Artisan, NPM)
      become_user: "{{ current_user }}"
      become_flags: '-i'
      shell: |
        cp -n .env.example .env || true
        sed -i "s/^DB_DATABASE=.*/DB_DATABASE={{ item.db }}/" .env
        sed -i "s/^DB_USERNAME=.*/DB_USERNAME={{ item.user }}/" .env
        sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD={{ db_pass }}/" .env
        sed -i "s|^APP_URL=.*|APP_URL=http://{{ item.name }}.test|" .env
        sed -i "s/^QUEUE_CONNECTION=.*/QUEUE_CONNECTION=redis/" .env
        
        php -d memory_limit=-1 {{ composer_bin }} install --no-interaction --prefer-dist
        php artisan key:generate
        php artisan migrate --force
        php artisan storage:link
        
        npm install
        npm run build
      args:
        chdir: "{{ projects_dir }}/{{ item.name }}"
      loop: "{{ projects }}"

    # ==================================================================
    # SHARED PERMISSIONS (any www-data user can edit)
    # ==================================================================
    - name: Set Project Directory Permissions
      file:
        path: "{{ projects_dir }}/{{ item.name }}"
        state: directory
        recurse: yes
        group: "{{ shared_group }}"
        mode: 'g+rwX'  # group read/write/execute
      loop: "{{ projects }}"

    - name: Set Storage Permissions (writable by all)
      file:
        path: "{{ projects_dir }}/{{ item.name }}/storage"
        state: directory
        recurse: yes
        group: "{{ shared_group }}"
        mode: '2775'  # setgid + rwx for group
      loop: "{{ projects }}"

    - name: Set Bootstrap Cache Permissions
      file:
        path: "{{ projects_dir }}/{{ item.name }}/bootstrap/cache"
        state: directory
        recurse: yes
        group: "{{ shared_group }}"
        mode: '2775'
      loop: "{{ projects }}"

    # ==================================================================
    # NGINX CONFIGURATION
    # ==================================================================
    - name: Create Nginx Server Blocks for Projects
      copy:
        dest: "/etc/nginx/sites-available/{{ item.name }}.test"
        content: |
          server {
              listen 80;
              listen [::]:80;
              server_name {{ item.name }}.test;
              root {{ projects_dir }}/{{ item.name }}/public;

              add_header X-Frame-Options "SAMEORIGIN";
              add_header X-Content-Type-Options "nosniff";

              index index.php;

              charset utf-8;

              location / {
                  try_files $uri $uri/ /index.php?$query_string;
              }

              location = /favicon.ico { access_log off; log_not_found off; }
              location = /robots.txt  { access_log off; log_not_found off; }

              error_page 404 /index.php;

              location ~ \.php$ {
                  fastcgi_pass unix:{{ php_fpm_sock }};
                  fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                  fastcgi_split_path_info ^(.+\.php)(/.+)$;
                  fastcgi_index index.php;
                  include fastcgi_params;
                  fastcgi_param PATH_INFO $fastcgi_path_info;
              }

              location ~ /\.(?!well-known).* {
                  deny all;
              }
          }
      loop: "{{ projects }}"

    - name: Enable Nginx Server Blocks
      file:
        src: "/etc/nginx/sites-available/{{ item.name }}.test"
        dest: "/etc/nginx/sites-enabled/{{ item.name }}.test"
        state: link
      loop: "{{ projects }}"

    - name: Add Projects to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^127\\.0\\.0\\.1\\s+{{ item.name }}\\.test"
        line: "127.0.0.1 {{ item.name }}.test"
        state: present
      loop: "{{ projects }}"

    - name: Test Nginx Configuration
      command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: false

    - name: Display Nginx Test Errors
      debug:
        msg: 
          - "Nginx configuration test failed!"
          - "Error output: {{ nginx_test.stderr }}"
      when: nginx_test.rc != 0

    - name: Fail if Nginx Test Failed
      fail:
        msg: "Nginx configuration is invalid. Please check the error message above."
      when: nginx_test.rc != 0

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
      when: nginx_test.rc == 0

    # ==================================================================
    # SUPERVISOR (Horizon)
    # ==================================================================
    - name: Create Horizon Supervisor Configs
      copy:
        dest: "/etc/supervisor/conf.d/{{ item.name }}-horizon.conf"
        content: |
          [program:{{ item.name }}-horizon]
          process_name=%(program_name)s
          command={{ php_bin }} {{ projects_dir }}/{{ item.name }}/artisan horizon
          autostart=true
          autorestart=true
          user=www-data
          redirect_stderr=true
          stdout_logfile={{ projects_dir }}/{{ item.name }}/storage/logs/horizon.log
          stopwaitsecs=3600
      loop: "{{ projects }}"
      register: supervisor_config

    - name: Reload Supervisor
      block:
        - command: supervisorctl reread
          when: supervisor_config.changed
        - command: supervisorctl update
          when: supervisor_config.changed
        - command: "supervisorctl restart {{ item.name }}-horizon"
          loop: "{{ projects }}"
          ignore_errors: yes

    - name: Final Status
      command: supervisorctl status
      register: final_status

    - name: 🏁 PROJECT SETUP COMPLETE 🏁
      debug:
        msg: 
          - "All projects configured successfully!"
          - "Projects directory: {{ projects_dir }}"
          - "Any user in '{{ shared_group }}' group can edit projects"
          - "Run 'newgrp www-data' or logout/login to apply group"
          - "Horizon Status:"
          - "{{ final_status.stdout_lines }}"
